# Generated by Django 4.2.3 on 2023-12-02 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Members",
            fields=[
                ("name", models.CharField(max_length=100)),
                ("email", models.CharField(max_length=100)),
                (
                    "id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
            ],
        ),
    ]
