# Generated by Django 4.2.3 on 2024-01-19 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Captain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("CaptainId", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="ContainerBoat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ContainerBoatID", models.IntegerField(default=0)),
                ("Tonnage", models.IntegerField(default=0)),
                ("Country", models.CharField(max_length=200)),
                ("arrivalTime", models.TimeField()),
                ("departureTime", models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("UserId", models.AutoField(primary_key=True, serialize=False)),
                ("Name", models.CharField(max_length=200)),
                ("Password", models.CharField(max_length=200)),
                ("Role", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="TugBoat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CurrentStatus", models.CharField(max_length=200)),
                ("TugBoatId", models.IntegerField(default=0)),
                (
                    "CaptainId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="system.captain"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                ("TaskId", models.AutoField(primary_key=True, serialize=False)),
                ("ReqauriedTugBoat", models.IntegerField(default=0)),
                ("startTime", models.TimeField()),
                ("endTime", models.TimeField()),
                ("Action", models.CharField(max_length=200)),
                ("BerthId", models.IntegerField(default=0)),
                (
                    "ContainerBoatID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="system.containerboat",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ScheduleEntry",
            fields=[
                (
                    "ScheduleEntryId",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("State", models.CharField(max_length=10)),
                (
                    "TaskId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="system.task"
                    ),
                ),
                ("listOfTugBoats", models.ManyToManyField(to="system.tugboat")),
            ],
        ),
    ]
