# Generated by Django 4.2.3 on 2024-01-22 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0002_captain_containerboat_user_tugboat_task_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scheduleentry",
            name="State",
            field=models.CharField(
                choices=[("Scheduled", "Scheduled"), ("Completed", "Completed")],
                default="Scheduled",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="Action",
            field=models.CharField(
                choices=[("Arrival", "Arrival"), ("Departure", "Departure")],
                default="Arrival",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="tugboat",
            name="CurrentStatus",
            field=models.CharField(
                choices=[
                    ("Free", "Free"),
                    ("Busy", "Busy"),
                    ("Maintenance", "Maintenance"),
                ],
                default="Free",
                max_length=20,
            ),
        ),
    ]
