# Generated by Django 4.2.3 on 2024-01-22 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0003_alter_scheduleentry_state_alter_task_action_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="containerboat",
            name="arrivalTime",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="containerboat",
            name="departureTime",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="task",
            name="endTime",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="task",
            name="startTime",
            field=models.DateTimeField(),
        ),
    ]
