# Generated by Django 4.2.3 on 2024-01-22 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0004_alter_containerboat_arrivaltime_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="State",
            field=models.CharField(
                choices=[("Scheduled", "Scheduled"), ("Unschedule", "Unschedule")],
                default="Unscheduled",
                max_length=10,
            ),
        ),
    ]
