# Generated by Django 4.2.3 on 2024-01-22 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0005_task_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="State",
            field=models.CharField(
                choices=[("Scheduled", "Scheduled"), ("Unschedule", "Unschedule")],
                default="Unschedule",
                max_length=10,
            ),
        ),
    ]
