# Generated by Django 4.2.7 on 2024-02-20 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_alter_task_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkingTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StartTime', models.DateTimeField()),
                ('EndTime', models.DateTimeField()),
                ('TugBoatId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.tugboat')),
            ],
        ),
    ]
