# Generated by Django 4.2.7 on 2024-02-20 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0007_workingtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='tugboat',
            name='EndWorkingTime',
            field=models.DateTimeField(default='2021-01-01T00:00:00Z'),
        ),
        migrations.AddField(
            model_name='tugboat',
            name='StartWorkingTime',
            field=models.DateTimeField(default='2021-01-01T00:00:00Z'),
        ),
        migrations.DeleteModel(
            name='WorkingTime',
        ),
    ]
