# Generated by Django 4.2.7 on 2024-02-20 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0008_tugboat_endworkingtime_tugboat_startworkingtime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tugboat',
            name='EndWorkingTime',
            field=models.TimeField(default='T08:00:00Z'),
        ),
        migrations.AlterField(
            model_name='tugboat',
            name='StartWorkingTime',
            field=models.TimeField(default='T00:00:00Z'),
        ),
    ]
