# Generated by Django 5.0.2 on 2024-02-20 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0009_alter_tugboat_endworkingtime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='State',
            field=models.CharField(choices=[('Scheduled', 'Scheduled'), ('Unscheduled', 'Unscheduled')], default='Unscheduled', max_length=100),
        ),
    ]
