# Generated by Django 4.2.7 on 2024-02-20 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0010_alter_task_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='TaskId',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
