# Generated by Django 5.0.2 on 2024-02-23 16:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0011_alter_task_taskid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='captain',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='captain', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='captain',
            name='CaptainId',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='task',
            name='TaskId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
