# Generated by Django 4.2.7 on 2024-02-25 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0012_captain_user_alter_captain_captainid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scheduler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Account', models.CharField(default='SC0001', max_length=200, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('SchedulerId', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Members',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.RemoveField(
            model_name='captain',
            name='user',
        ),
        migrations.AddField(
            model_name='captain',
            name='Account',
            field=models.CharField(default='CP0001', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='captain',
            name='CaptainId',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='tugboat',
            name='CaptainId',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tugboat', to='system.captain'),
        ),
        migrations.AlterField(
            model_name='tugboat',
            name='TugBoatId',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
