# Generated by Django 4.2.7 on 2024-02-25 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0013_scheduler_delete_members_delete_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captain',
            name='Account',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='scheduler',
            name='Account',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
