# Generated by Django 4.2.7 on 2024-02-25 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0014_alter_captain_account_alter_scheduler_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='containerboat',
            name='ContainerBoatID',
            field=models.CharField(max_length=200),
        ),
    ]
