# Generated by Django 4.2.7 on 2024-02-26 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0016_captain_user_scheduler_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Berth',
            fields=[
                ('BerthId', models.IntegerField(primary_key=True, serialize=False)),
                ('ContainerBoat', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='berth', to='system.containerboat')),
            ],
        ),
    ]
