# Generated by Django 5.0.2 on 2024-02-25 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0016_captain_user_scheduler_user'),
        ('system', '0017_alter_captain_account_alter_scheduler_account'),
    ]

    operations = [
    ]
