# Generated by Django 4.2.7 on 2024-02-26 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0018_alter_berth_containerboat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='berth',
            name='ContainerBoat',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='berth', to='system.containerboat'),
        ),
    ]
