# Generated by Django 5.0.2 on 2024-02-25 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0018_merge_20240226_0019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='captain',
            name='user',
        ),
        migrations.RemoveField(
            model_name='scheduler',
            name='user',
        ),
    ]
