# Generated by Django 5.0.2 on 2024-02-26 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0019_remove_captain_user_remove_scheduler_user'),
        ('system', '0020_alter_berth_containerboat'),
    ]

    operations = [
    ]
