# Generated by Django 4.2.7 on 2024-02-28 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0021_merge_20240226_2159'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ('TaskId',)},
        ),
    ]
