# Generated by Django 5.0.2 on 2024-02-28 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0025_alter_berth_containerboat_alter_task_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='ReqauriedTugBoat',
            new_name='RequiredTugBoat',
        ),
    ]
