# Generated by Django 4.2.7 on 2024-02-29 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0026_rename_reqauriedtugboat_task_requiredtugboat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='RequiredTugBoat',
            field=models.IntegerField(),
        ),
    ]
