# Generated by Django 4.2.7 on 2024-02-29 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0027_alter_task_requiredtugboat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='RequiredTugBoat',
            field=models.IntegerField(default=0),
        ),
    ]
