# Generated by Django 4.2.7 on 2024-03-03 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0028_alter_task_requiredtugboat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='containerboat',
            name='arrivalTime',
        ),
        migrations.RemoveField(
            model_name='containerboat',
            name='departureTime',
        ),
        migrations.RemoveField(
            model_name='scheduleentry',
            name='State',
        ),
        migrations.RemoveField(
            model_name='task',
            name='endTime',
        ),
        migrations.AddField(
            model_name='scheduleentry',
            name='EndTime',
            field=models.DateTimeField(default='2024-01-01 00:00:00'),
        ),
        migrations.AddField(
            model_name='scheduleentry',
            name='PublishTime',
            field=models.DateTimeField(default='2024-01-01 00:00:00'),
        ),
        migrations.AddField(
            model_name='scheduleentry',
            name='StartTime',
            field=models.DateTimeField(default='2024-01-01 00:00:00'),
        ),
        migrations.AddField(
            model_name='scheduleentry',
            name='Status',
            field=models.CharField(choices=[('Scheduled', 'Scheduled'), ('Completed', 'Completed'), ('Conformed', 'Conformed')], default='Scheduled', max_length=10),
        ),
        migrations.AlterField(
            model_name='task',
            name='Action',
            field=models.CharField(choices=[('INBOUND', 'INBOUND'), ('OUTBOUND', 'OUTBOUND')], default='INBOUND', max_length=10),
        ),
        migrations.AlterField(
            model_name='task',
            name='startTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
