# Generated by Django 4.2.7 on 2024-03-03 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0031_alter_task_starttime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='startTime',
            field=models.DateTimeField(default='2022-01-01 T00:00:00Z'),
        ),
    ]
