# Generated by Django 4.2.7 on 2024-03-03 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0033_alter_task_starttime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleentry',
            name='EndTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scheduleentry',
            name='StartTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
