# Generated by Django 5.0.2 on 2024-03-04 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0034_alter_scheduleentry_endtime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleentry',
            name='Status',
            field=models.CharField(choices=[('Scheduled', 'Scheduled'), ('Completed', 'Completed'), ('Confirmed', 'Confirmed')], default='Scheduled', max_length=10),
        ),
    ]
