# Generated by Django 5.0.2 on 2024-03-06 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0035_alter_scheduleentry_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='ContainerBoatID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='system.containerboat'),
        ),
    ]
