<<<<<<< HEAD
# Generated by Django 5.0.2 on 2024-03-13 14:42
=======
# Generated by Django 5.0.2 on 2024-03-13 14:40
>>>>>>> 1a6d9b49ff9bc661710ec54ff23aad3b8354cf78

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0039_task_taskmanual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleentry',
            name='PublishTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
