# Generated by Django 5.0.2 on 2024-03-13 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0039_task_taskmanual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleentry',
            name='PublishTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
