# Generated by Django 5.0.2 on 2024-03-13 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0040_alter_scheduleentry_publishtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tugboat',
            name='EndWorkingTime',
            field=models.TimeField(default='08:00:00'),
        ),
        migrations.AlterField(
            model_name='tugboat',
            name='StartWorkingTime',
            field=models.TimeField(default='00:00:00'),
        ),
    ]
