# Generated by Django 5.0.2 on 2024-03-22 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0041_alter_tugboat_endworkingtime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='berth',
            name='ContainerBoat',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='berth', to='system.containerboat'),
        ),
    ]
